server:
  port: 3002
  jetty:
    max-http-form-post-size: 10000000
spring:
  application:
    name: appointment-management
  datasource:
    url: jdbc:postgresql://10.43.100.173:3002/postgres
    username:  appointment
    password: password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # Hikari
    hikari:
      maximum-pool-size: 10 
  jpa:
    hibernate:
      ddl-auto: none 
    generate-ddl: true
    #open-in-view: true
  activemq:
    broker-url: tcp://10.43.100.173:3016
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 10
  security:
    oauth2:
     resourceserver:
       jwt:
         jwk-set-uri: http://10.43.100.173:3003/auth/realms/appointment-realm/protocol/openid-connect/certs  

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  metrics:
      export:
         prometheus:
              enabled: true
              
