server:
   port: 3001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  http://10.43.100.173:3003/auth/realms/appointment-realm/protocol/openid-connect/certs  

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
endpoint:
     availability:
         manager: http://appointmentmanagement:3002/appointment/availability
     booking:
         manager: http://appointmentmanagement:3002/appointment/booking
     cancel:
         manager: http://appointmentmanagement:3002/appointment/cancel
     find:
         manager: http://appointmentmanagement:3002/appointment/find  
              
