server:
   port: 8083

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  http://192.168.0.7:8091/auth/realms/appointment-realm/protocol/openid-connect/certs  

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
endpoint:
     availability:
         manager: http://localhost:9191/appointment/availability
     booking:
         manager: http://localhost:9191/appointment/booking
     cancel:
         manager: http://localhost:9191/appointment/cancel
     find:
         manager: http://localhost:9191/appointment/find  