server:
  port: 3003

spring:
  application:
    name: interoperability
  activemq:
    broker-url: tcp://10.43.100.173:3016
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 10

endpoint:
  availability:
      ips: http://ipsmockup:3003/ips/availability
  booking:
      ips: http://ipsmockup:3003/ips/booking
  cancel:
      ips: http://ipsmockup:3003/ips/cancel    
management:
  endpoints: 
    web:
      exposure: 
        include:
        - "*"      
