server:
  port: 3003

spring:
  application:
    name: interoperability
  activemq:
    broker-url: tcp://10.43.100.173:3016
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 10

endpoint:
  availability:
      ips: http://ipsmockup:3004/ips/availability
  booking:
      ips: http://ipsmockup:3004/ips/booking
  cancel:
      ips: http://ipsmockup:3004/ips/cancel
  notification:
      booking: http://notification:80/V1/CorreoElectronico/EmailReservarCita
      cancel: http://notification:80/V1/CorreoElectronico/EmailCancelarCita
management:
  endpoints: 
    web:
      exposure: 
        include:
        - "*"      
